### ISSUE TITLE
Error 500 - Unable to import an app

### ISSUE THREAD

**Issue by countnazgul** [qlik-oss/core#1] opened 2018-08-21 12:44 UTC
Trying to import qvf using the core REST API (`/v1/apps/import`) so i can use the ABAC capability. Using the docker-compose and the node files below returns error 500 (internal server error). The container stdout was a bit more informative (`Unsupported file format version`) but still not clear why. As a source file im using any of the qvf files that are shipped with QS Desktop (June 2018 at the moment). Ive tried moving the qvfs from the default folder but the result was the same 

(pasting `allow.txt` as well if needed)

docker-compose file:
```dockerfile
version: "3.0"

services:

  qix-engine:
    image: qlikcore/engine:12.215.0
    container_name: qix-engine-test
    command: -S AcceptEULA=yes -S LicenseServiceUrl=http://licenses:9200 -S TrafficLogVerbosity=1 -S SystemLogVerbosity=5 -S DocumentDirectory=/home/nobody/apps -S ValidateJsonWebTokens=2 -S JsonWebTokenPath=/home/nobody/certs/2public.pem -S EnableABAC=1 -S SystemAllowRulePath=/home/nobody/abac/allow.txt
    volumes:
      - C:/Users/USER/Documents/DOCKER/dockerdata/qlik/apps:/home/nobody/apps
      - C:/Users/USER/Documents/DOCKER/dockerdata/qlik/certs:/home/nobody/certs
      - C:/Users/USER/Documents/DOCKER/dockerdata/qlik/abac:/home/nobody/abac
    ports:
      - 19076:9076
      - 9090:9090
      - 9098:80
    labels:
      qix-engine: "qix-engine-test"

  licenses:
    image: qlikcore/licenses:1.0.5
    environment:
      - LICENSES_SERIAL_NBR=XXXXXXX
      - LICENSES_CONTROL_NBR=XXXXX
      - LICENSES_LOG_LEVEL=debug
    ports:
      - 9200:9200
```
node script
```javascript
const jwt = require('jsonwebtoken');
const rp = require('request-promise');
const fs = require('fs');

(async () => {
const qvf = fs.readFileSync('C:/Users/USER/Documents/Qlik/Sense/Apps/Executive Dashboard.qvf')

let token = await getJWT();

var options = {
    method: 'POST',
    uri: 'http://localhost:19076/v1/apps/import?name=test.qvf&mode=new',
    body: {
        filedata: qvf
    },
    headers: {
        "Authorization": "Bearer " + token
    },
    json: true
};


rp(options)
    .then(function (parsedBody) {
        console.log('parsedBody', parsedBody)
    })
    .catch(function (err) {
        console.log(err.message)
    });

})();

async function getJWT() {
    let jwtEncryptionKey = fs.readFileSync('../certs/2private.pem');


    token = await jwt.sign(
        {
            "sub": "test",
            "employeeType": "admin"
        },
        Buffer.from(jwtEncryptionKey, 'base64'),
        { "algorithm": "RS256" }
    )
    return token;
}    
```

allow.txt

```
user.id = "test" && resource._actions = "*"
```

output log:
````
{"timestamp":"2018-08-21T11:21:35.126Z","log_type":"System","logseverity":"INFO","thread_id":150968064,"user_id":"test","tenant_id":"","app_id":"0","message":"ServerPlugin: ExecutePluginCompositeFunc plugin exception [0]."}
{"timestamp":"2018-08-21T11:21:35.126Z","log_type":"System","logseverity":"DEBUG","thread_id":150968064,"user_id":"test","tenant_id":"","app_id":"0","message":"ExtendedException: Type '3004' thrown. Message: 'Unsupported file format version' and additional debug info: ''"}
{"timestamp":"2018-08-21T11:21:35.126Z","log_type":"System","logseverity":"DEBUG","thread_id":150968064,"user_id":"test","tenant_id":"","app_id":"0","message":"ExtendedException: Type '1007' thrown. Message: 'App invalid' and additional debug info: ''"}
{"timestamp":"2018-08-21T11:21:35.126Z","log_type":"System","logseverity":"WARN","thread_id":150968064,"user_id":"test","tenant_id":"","app_id":"0","message":"TheServer: Exception: 500, import app"}```

**Comment by wennmo** [comment] 2018-08-22 14:11
Hi @countnazgul ,
Thanks for submitting the issue! I have taken a look at the code attached and I can reproduce your problem. Actually this scenario contains multiple problems that needs to be addressed by us.

The documentation regarding how to add the qvf to the body is incorrect. The following code snippet shows how it can be done.

```
var options = {
    method: 'POST',
    uri: 'http://localhost:19076/v1/apps/import?name=test.qvf&mode=new',
    body: fs.createReadStream("C:/Users/USER/Documents/Qlik/Sense/Apps/Executive Dashboard.qvf"),
    headers: {
        "Authorization": "Bearer " + token,
    },
};
```

Even though the import now succeeds you will see a problem with the ruleset that you apply. The mapping between the `jwt.sub` and `user.id` does not seem to be in place yet (even though the documentation states so). As a workaround you can use `user.sub = “test” && resource._actions = “*”` until the problem is resolved.

Can you give it a try?

Regards,
Mattias

**Comment by countnazgul** [comment] 2018-08-22 15:49
Thank you very much for looking into this Mattias!

It kinda worked :)
The file was imported when ive switched off the ABAC (`EnableABAC=0`) If its not switched off i was getting 403 error (although im fairly sure that nothing had changed on the certificates (will need to double check on my side)). 

Couple of more questions:

* /import?**name=test.qvf**&mode=new - after the import the filename should be `test.qvf`? (because after the impot the file name was self generated `195eb28c-cfec-4daa-b42b-573de0697877.qvf`) or this is used only in `mode=autoreplace`?
* when importing an app with `ValidateJsonWebTokens=2` i need to provide `sub` in the `jwt`. this means that the uploaded app will be accessible only for the provided `sub` or the `sub` is just used for authentication purposes and who have access to the app is defined in the allow/deny rules?

Thanks!
Stefan

**Comment by wennmo** [comment] 2018-08-23 06:52
Ok, at least a step in the right direction! It should be possible to import apps with ABAC enabled, so a bit curious about the `403` code you encountered. Can you share any logs? Can you also try to remove the setting for `DocumentDirectory` as a parameter to rule out that this is due to access permissions on mounted folders?

Regarding your two questions:

1.	` /import?name=test.qvf&mode=new` - This is a known bug and fix is on the way, and hopefully included in the next engine release.
2.	`jwt.sub` will be set as the owner of the imported app. Access to the imported app for other users will be controlled by the allow/deny rules.

Regards,
Mattias

**Comment by countnazgul** [comment] 2018-08-23 08:43
Yes! Removed `DocumentDirectory`  and there is no `403` . The apps are uploaded in `/home/nobody/Qlik/Sense/Apps/default` (is this because im on Windows and the mounted folders permissions cant be altered nicely)

**Comment by wennmo** [comment] 2018-08-24 11:09
* The REST-API documentation for the import endpoint was updated in https://github.com/qlik-oss/core-website/pull/387.
* The user attribute documentation for ABAC was updated in https://github.com/qlik-oss/core-website/pull/386

**Comment by countnazgul** [comment] 2018-08-24 11:17
Thanks!

**Comment by wennmo** [comment] 2018-08-24 11:35
We created a separate task for adding examples for importing apps when using the ABAC feature, since both configuration and scenario can easily become complex. 

https://github.com/qlik-oss/core-authorization/issues/7

Lets handle any outstanding questions in this scenario as separate issues, and close this one for now.

Thanks for a well-described and informative issue @countnazgul 👍

**Closed by wennmo** 2018-08-24 11:35 UTC
Labels: bug
